

services:
  db:
    image: postgres:15
    restart: always
    container_name: farmhouse_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salasanatähän
      POSTGRES_DB: farmhouse
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/bookings.sql:/docker-entrypoint-initdb.d/bookings.sql

  backend:
    build: ./backend
    container_name: farmhouse_backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:salasanatähän!@db:5432/farmhouse
      JWT_SECRET: your_jwt_secret (ei ole tämä)
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  db_data:
